#!/bin/bash

touch sample.txt

for file in $home/home/workspace/SWE_2021_41_2023_2_week_4-main/files/*
do
    	echo "${file##*/}" >> sample.txt
   	    echo "${file##*/}"
done

for line in $(cat sample.txt)
do

    	firstchar=${line:0:1}

    	mv $home/home/workspace/SWE_2021_41_2023_2_week_4-main/files/$line $home/home/workspace/SWE_2021_41_2023_2_week_4-main/$firstchar

done
